Header section
Sunmade1/My-portfolio pull request #1
Opened 2022-07-12 17:11 UTC by Sunmade1

The first pull request for the first project

2022-07-17 18:57 UTC, brainconnect93 commented on index.html
> +        <li id="shift"><a href="#Portfolio">Portfolio</a></li>
the list tag in line 14 should be an header either h1-h6

2022-07-17 18:58 UTC, brainconnect93 commented on index.html
> +        </ul>
kindly add the message icon here

2022-07-17 19:00 UTC, brainconnect93 commented on index.html
> +            <td>Codepen</td>
it's nice using the table HTML semantic but I would suggest you have this section writing inform of a list tag

2022-07-17 19:02 UTC, brainconnect93 requested changes
Hi @Sunmade1 👏 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/78634841/179420543-368e2514-aa7d-4033-8f2d-aa295283358f.png)

## REQUIRED CHANGES

2022-07-18 21:06 UTC, sunmadetek commented on index.html
> +        <li id="shift"><a href="#Portfolio">Portfolio</a></li>
You header element nested in the list  tag?

2022-08-07 20:53 UTC, merged